language: python
sudo: false
python:
- 3.6
env:
- DJANGO_SETTINGS_MODULE=seminar.settings.test
services:
- postgresql
install:
- pip install -r requirements-dev.txt
before_script:
- ./manage.py migrate
script:
- pytest
after_success:
- codecov
